# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c1ae1d8e-1591-4adc-868f-940ec1ccd5ab'
  imageRepository: 'gerromesiegerdjangoreactapp'
  containerRegistry: 'dockerhub1.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy_to_Staging
  displayName: Deploy to a remote vm server 
  jobs:
  - job: Deploy_to_staging
    displayName: Deploy to staging env
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadSecureFile@1
      name: ssh_key
      inputs:
        secureFile: 'azurevmkey'
    - script: |
        sudo chmod 400 $(ssh_key.secureFilePath)
        ssh -i $(ssh_key.secureFilePath) -o StrictHostKeyChecking=no gerrome@52.188.172.231 "cd Django-React-App && docker-compose up"     
